<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="15.1.*" />
    <PackageReference Include="DeepCloner" Version="0.10.4" />
    <PackageReference Include="FluentValidation" Version="12.1.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.0" />
    <PackageReference Include="MediatR" Version="13.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Hangfire.Core">
      <HintPath>..\..\..\..\.nuget\packages\hangfire.core\1.8.21\lib\netstandard2.0\Hangfire.Core.dll</HintPath>
    </Reference>
    <Reference Include="MongoDB.Bson">
      <HintPath>..\..\..\..\.nuget\packages\mongodb.bson\3.5.0\lib\net6.0\MongoDB.Bson.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
